export const CREATE_TODO = "CREATE_TODO";
export const RETRIEVE_TODOS = "RETRIEVE_TODOS";
export const RETRIEVE_TODO = "RETRIEVE_TODO";
export const UPDATE_TODO = "UPDATE_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const DELETE_ALL_TODOS = "DELETE_ALL_TODOS";
export const SEARCH_TODOS = "SEARCH_TODOS"